name: Ejecutar script de Azure

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  build:
    runs-on: ubuntu-latest  # Cambia esto si prefieres otro sistema operativo

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Ejecutar script PowerShell
      shell: pwsh
      run: |
        ./azure.ps1
